services:
  test:
    build:
      context: .
      args:
        REQUIREMENTS_FILE: requirements-dev.lock
    command: pytest --maxfail=5 --disable-warnings -v
    restart: "no"

volumes:
  postgres_test_data: