name: lithium_bom

services:
  web:
    build: .
    command: gunicorn bom.wsgi:application --bind 0.0.0.0:${API_PORT}
    volumes:
      - static_volume:/app/staticfiles
    expose:
      - ${API_PORT}
    depends_on:
      - db
    restart: always
    env_file:
      - ./.env
  nginx:
    image: nginx:alpine
    volumes:
      - static_volume:/home/app/web/staticfiles
      - ./nginx/templates:/etc/nginx/templates/
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - web
    restart: always
    env_file:
      - ./.env
  db:
    image: postgres:17-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    env_file:
      - ./.env
  backup:
    image: postgres:17-alpine
    env_file:
      - path: ./.env
        required: true
      - path: ./.env.db
        required: false
    volumes:
      - ./postgres_backup:/backups
    entrypoint: >
      sh -c "
      echo '0 1 * * * PGPASSWORD=$POSTGRES_PASSWORD pg_dump -h db -p $SQL_PORT -U $POSTGRES_USER -d $POSTGRES_DB | gzip > /backups/dump_${POSTGRES_DB}_$(date +%Y-%m-%d_%H%M%S)GMT.sql.gz &&
      ls -tp /backups | grep -v /$ | tail -n +8 | xargs -I {} rm -- /backups/{}' | crontab - &&
      crond -f
      "
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
