name: lithium_bom

services:
  web:
    build: .
    command: gunicorn bom.wsgi:application --bind 0.0.0.0:${API_PORT}
    env_file:
      - ./.env
    volumes:
      - static_volume:/app/staticfiles
    expose:
      - ${API_PORT}
    depends_on:
      - db
    restart: always  # Critical service, should always restart
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - web
    restart: always  # Reverse proxy, should always be available
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
    restart: always  # Database, critical for the application
  backup:
    image: postgres:16-alpine
    env_file:
      - ./.env.db
    volumes:
      - ./postgres_backup:/backups
    entrypoint: >
      sh -c "
      mkdir -p /backups &&
      while true; do
        pg_dump -U $POSTGRES_USER -d $POSTGRES_DB | gzip > /backups/dump_$POSTGRES_DB_$(date +%Y%m%d%H%M%S).sql.gz &&
        ls -tp /backups | grep -v '/$' | tail -n +8 | xargs -I {} rm -- /backups/{}; 
        sleep {BACKUP_INTERVAL};
      done
      "
    depends_on:
      - db
    restart: unless-stopped  # Backup service, can be manually stopped if needed

volumes:
  postgres_data:
  static_volume:
