version: '3.8'
# name: barg_bom-dev

services:
  web:
    image: djangobom
    build:
      context: .
      dockerfile: Dockerfile
    # This overrides the CMD in the Dockerfile
    command: 
      - "sh"
      - "-c"
      - |
        python -Xfrozen_modules=off /usr/local/lib/python3.12/site-packages/debugpy --wait-for-client --listen 0.0.0.0:5678 \
        manage.py runserver 0.0.0.0:8000 --nothreading --noreload
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
      - 5678:5678
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:16
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=bom_user
      - POSTGRES_PASSWORD=bom_pass
      - POSTGRES_DB=bom_db_dev

volumes:
  postgres_data_dev:
