# Generated by Django 5.0.3 on 2024-03-24 01:50

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bom", "0048_alter_organization_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sellerpart",
            name="unit_cost",
            field=djmoney.models.fields.MoneyField(
                decimal_places=0, default_currency="USD", max_digits=19
            ),
        ),
    ]
