# Generated by Django 5.0.3 on 2025-04-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0050_alter_partrevision_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partrevision',
            name='revision',
            field=models.CharField(db_index=True, default='1', max_length=12),
        ),
    ]
