# Generated by Django 5.0.3 on 2025-05-20 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0051_alter_partrevision_revision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bom.organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='part',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bom.organization'),
        ),
        migrations.AlterField(
            model_name='part',
            name='primary_manufacturer_part',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_manufacturer_part', to='bom.manufacturerpart'),
        ),
        migrations.AlterField(
            model_name='partrevision',
            name='tolerance',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bom.organization'),
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bom.organization'),
        ),
    ]
