# Generated by Django 6.1 on 2026-09-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0056_remove_customer_default_profit_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeta',
            name='language',
            field=models.CharField(choices=[('fa', 'Persian'), ('en', 'English')], default='fa-IR', max_length=10),
        ),
    ]
